<a href="https://colab.research.google.com/github/WlrdTan/assignment_robotarm2D/blob/main/robotArmFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
""" Kinematic chain of a robot arm (planar)
    Assignment
"""

' Kinematic chain of a robot arm (planar)\n    Assignment \n'


![](https://github.com/eraldoribeiro/assignment_robotarm2D/blob/main/robotArm01.png?raw=1)
*Figure 1*: A two-dimensional articulated arm. The articulated structure has 3 local coordinate frames each one centered at a joint. For each part, the local x-axis is aligned with the part.  

Consider the arm structure shown in Figure 1. Assume the following values for the arm configuration:
- The location of the first joint (i.e., the one that is attached to the ground support) is ${\bf p}_1 = \left(3,2\right)^\mathsf{T}$.
- The lengths of the parts are $L_1 = 5$ and  $L_2 = 8$.

In [ ]:
import numpy as np
import math as mph

### Question 1

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [21]:
import numpy as np

# Given values
L1 = 5
L2 = 8
p1 = np.array([3, 2])
phi1 = 0.0
phi2 = 0.0


def rotation_2d(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.array([
        [ c, -s, 0 ],
        [ s,  c, 0 ],
        [ 0,  0, 1 ]
    ])

def T0_1(phi1, p1):
    T = np.eye(3)
    T[0, 2] = p1[0]
    T[1, 2] = p1[1]
    return T @ rotation_2d(phi1)

def T1_2(phi2, L1):
    T_translate = np.eye(3)
    T_translate[0, 2] = L1
    return T_translate @ rotation_2d(phi2)

def T2_3(L2):
    T = np.eye(3)
    T[0, 2] = L2
    return T

# Build each transform
T01 = T0_1(phi1, p1)
T12 = T1_2(phi2, L1)
T23 = T2_3(L2)

print("T0,1 =\n", T01)
print("\nT1,2 =\n", T12)
print("\nT2,3 =\n", T23)




T0,1 =
 [[1. 0. 3.]
 [0. 1. 2.]
 [0. 0. 1.]]

T1,2 =
 [[1. 0. 5.]
 [0. 1. 0.]
 [0. 0. 1.]]

T2,3 =
 [[1. 0. 8.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Question 2

Write the matrices that represent each local frame w.r.t. the global frame $\mathcal F\{0\}$. The transformations you need to write are $T_{0,1}$, $T_{0,2}$, and $T_{0,3}$.

In [27]:
import numpy as np

p1 = np.array([3, 2])
L1 = 5
L2 = 8

phi1 = np.deg2rad(0)
phi2 = np.deg2rad(0)

def transformation_matrix(rotation, translation):
    c = np.cos(rotation)
    s = np.sin(rotation)
    return np.array([
        [c, -s, translation[0]],
        [s,  c, translation[1]],
        [0,  0, 1]
    ])

T0_1 = transformation_matrix(phi1, p1)
T1_2 = transformation_matrix(phi2, np.array([L1, 0]))
T2_3 = transformation_matrix(0, np.array([L2, 0]))

T0_2 = T0_1 @ T1_2
T0_3 = T0_2 @ T2_3

print("T0,1 =\n", T0_1)
print("\nT0,2 =\n", T0_2)
print("\nT0,3 =\n", T0_3)






T0,1 =
 [[ 1. -0.  3.]
 [ 0.  1.  2.]
 [ 0.  0.  1.]]

T0,2 =
 [[1. 0. 8.]
 [0. 1. 2.]
 [0. 0. 1.]]

T0,3 =
 [[ 1.  0. 16.]
 [ 0.  1.  2.]
 [ 0.  0.  1.]]


### Question 3

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [26]:
import numpy as np

p1 = np.array([3, 2])
L1 = 5
L2 = 8

phi1 = np.deg2rad(0)
phi2 = np.deg2rad(0)

def homogeneous_transform(theta, translation):
    c, s = np.cos(theta), np.sin(theta)
    T = np.array([
        [c, -s, translation[0]],
        [s,  c, translation[1]],
        [0,  0, 1]
    ])
    return T

T0_1 = homogeneous_transform(phi1, p1)
T1_2 = homogeneous_transform(phi2, np.array([L1, 0]))
T2_3 = homogeneous_transform(0, np.array([L2, 0]))

print("T0,1 (F1 with respect to F0):\n", T0_1)
print("\nT1,2 (F2 with respect to F1):\n", T1_2)
print("\nT2,3 (F3 with respect to F2):\n", T2_3)






T0,1 (F1 with respect to F0):
 [[ 1. -0.  3.]
 [ 0.  1.  2.]
 [ 0.  0.  1.]]

T1,2 (F2 with respect to F1):
 [[ 1. -0.  5.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

T2,3 (F3 with respect to F2):
 [[ 1. -0.  8.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Question 4

Using the transformations from the previous questions, calculate the global coordinates of the middle point of each part of the robot arm when $\phi_1 = \pi/8$ and $\phi_2 = \pi/4$. Hint: the location of the middle point of part 1 is $(\frac{L_1}{2},0)^\mathsf{T}$ (w.r.t. frame $\mathcal F\{1\}$).

In [29]:
import numpy as np

L1 = 5
L2 = 8
phi1 = np.pi/8
phi2 = np.pi/4

p1 = np.array([3, 2])

def rotation_2d(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.array([
        [ c, -s, 0 ],
        [ s,  c, 0 ],
        [ 0,  0, 1 ]
    ])

def translate_2d(dx, dy):
    T = np.eye(3)
    T[0, 2] = dx
    T[1, 2] = dy
    return T

T0_1 = translate_2d(p1[0], p1[1]) @ rotation_2d(phi1)
T1_2 = translate_2d(L1, 0) @ rotation_2d(phi2)
T0_2 = T0_1 @ T1_2

mid_link1_local = np.array([L1/2, 0, 1])
mid_link2_local = np.array([L2/2, 0, 1])

mid_link1_global = T0_1 @ mid_link1_local
mid_link2_global = T0_2 @ mid_link2_local

print("Midpoint of link1 in global coords =", mid_link1_global[:2])
print("Midpoint of link2 in global coords =", mid_link2_global[:2])







Midpoint of link1 in global coords = [5.30969883 2.95670858]
Midpoint of link2 in global coords = [9.15013139 7.60893529]


### Question 5

Using the transformations from the previous questions, calculate the global coordinates of all the joint points and the end-effector location when $\phi_1 = \pi/4$ and $\phi_2 = \pi/8$.

In [30]:
import numpy as np

p1 = np.array([3, 2])
L1 = 5
L2 = 8

phi1 = np.pi / 4
phi2 = np.pi / 8

def homogeneous_transform(theta, translation):
    c, s = np.cos(theta), np.sin(theta)
    T = np.array([
        [c, -s, translation[0]],
        [s,  c, translation[1]],
        [0,  0, 1]
    ])
    return T

T0_1 = homogeneous_transform(phi1, p1)
T1_2 = homogeneous_transform(phi2, np.array([L1, 0]))
T2_3 = homogeneous_transform(0, np.array([L2, 0]))

T0_2 = T0_1 @ T1_2
T0_3 = T0_2 @ T2_3

joint1_global = p1
joint2_global = (T0_2 @ np.array([0, 0, 1]))[:2]
end_effector_global = (T0_3 @ np.array([0, 0, 1]))[:2]

print("Global coordinate of Joint 1:", joint1_global)
print("Global coordinate of Joint 2:", joint2_global)
print("Global coordinate of the End-Effector:", end_effector_global)






Global coordinate of Joint 1: [3 2]
Global coordinate of Joint 2: [6.53553391 5.53553391]
Global coordinate of the End-Effector: [ 9.59700136 12.92657017]


### Question 6

Write the matrix that represents the coordinate frame of the end effector w.r.t. frame  $\mathcal F\{1\}$, i.e., $T_{1,3}$

In [33]:
import numpy as np

phi1 = np.pi/6
phi2 = np.pi/4
L1 = 5
L2 = 8

def rotation_2d(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.array([
        [ c, -s, 0 ],
        [ s,  c, 0 ],
        [ 0,  0, 1 ]
    ])

def translate_2d(dx, dy):
    T = np.eye(3)
    T[0, 2] = dx
    T[1, 2] = dy
    return T

T1_2 = translate_2d(L1, 0) @ rotation_2d(phi2)

T2_3 = translate_2d(L2, 0)


T1_3 = T1_2 @ T2_3

print("T1,3 =\n", T1_3)





T1,3 =
 [[ 0.70710678 -0.70710678 10.65685425]
 [ 0.70710678  0.70710678  5.65685425]
 [ 0.          0.          1.        ]]


### Question 7

Write the matrix that represents the coordinate frame $\mathcal F\{1\}$ w.r.t. to the frame of the end effector

In [36]:
import numpy as np

phi2 = np.pi / 4
L1 = 5
L2 = 8

def rotation_2d(theta):
    c = np.cos(theta)
    s = np.sin(theta)
    return np.array([
        [ c, -s, 0 ],
        [ s,  c, 0 ],
        [ 0,  0, 1 ]
    ])

def translate_2d(dx, dy):
    T = np.eye(3)
    T[0, 2] = dx
    T[1, 2] = dy
    return T

T1_2 = translate_2d(L1, 0) @ rotation_2d(phi2)
T2_3 = translate_2d(L2, 0)

T1_3 = T1_2 @ T2_3

print("T1,3 =\n", T1_3)

T3_1 = np.linalg.inv(T1_3)

print("\nT3,1 =\n", T3_1)





Transformation matrix T1,3 (F3 with respect to F1):
[[ 0.8660254  -0.5        11.92820323]
 [ 0.5         0.8660254   4.        ]
 [ 0.          0.          1.        ]]

Transformation matrix T3,1 (F1 with respect to F3):
[[  0.8660254    0.5        -12.33012702]
 [ -0.5          0.8660254    2.5       ]
 [  0.           0.           1.        ]]
